### ISSUE TITLE
[iOS] ExecuteJavascript() does not work

### ISSUE THREAD

**Issue by neooleg** [HybridWebPlatform/Hybrid-Web-Platform#1]
## Abstract
The following code works on Android, but doesn't work on iOS
```
ExecuteJavascript("alert('test')")
```

**Comment by mr-wheelkers** [comment]
Javascript is working perfectly fine, the issue here was in WKWebView alert-handling process. That is why alerts were not working. Now Input, Alert and Yes/No dialogs are handled.
